wanix_customisations:
  - name: setup_uwusers
    roles:
      - setup_uwusers

  - name: wanix_base_tools
    roles:
      - name: install_git
      - name: install_yay
        deb_install: false

  - name: post_vm_clone
    roles:
      - post_clone_setup

  - name: setup_base_environment
    packages:
      - linux-headers
      - python-pip

  - name: nmcli_networking
    packages:
      - networkmanager
    roles:
      - setup_nmcli

  - name: cli_base_tools
    packages:
      - bind
      - nano
      - nmap
      - unzip
      - curl
      - neofetch
      - calc
      - zsh
      - screen

    roles:
      - name: configure_omzsh


  - name: cli_dev_tools
    packages:
      - packer
      - terraform
      - sshpass
      - direnv
      - docker
      - docker-compose
      - traceroute
      - sops
    roles:
      - name: install_bsm
        provides_pkgs:
          - bsm

  - name: nvidia_drivers
    packages:
      - nvidia-vaapi-driver
      - nvidia
      - firmware-misc-nonfree

  - name: x_server
    packages:
      - xorg
      - xinit

  - name: graphical_common
    packages:
      - firefox-developer-edition
      - clapper
      - gst-libav
      - sddm
      - gnome-font-viewer
      - gsfonts
      - thunar
      - eog

    roles:
      - name: setup_sddm

  - name: graphical_dev
    packages:
      - devtoys-bin
      - visual-studio-code-bin
      - rdesktop

  - name: graphical_editing
    packages:
      - davinci-resolve
      - nvidia-utils
      - opencl-nvidia

  - name: graphical_social
    packages:
      - discord
      - vesktop

  - name: graphical_sound
    packages:
      - easyeffects
      - pavucontrol
      - spotify-launcher

  - name: pipewire_sound_server
    roles:
      - name: install_pipewire_audio
        provides_pkgs:
          - pipewire

  - name: meaditha
    packages:
      - btop
      - bspwm
      - sxhkd
      - polybar
      - rofi
      - nitrogen
      - dunst
      - rxvt-unicode
      - imagemagick
      - kitty
      - python-gobject
      - scrot
    pip_packages:
      - pycairo
      - name: pywal16
        install: git+https://github.com/eylles/pywal16
      - colorz

    roles:
      - add_fonts

  - name: bluetooth
    packages:
      - blueman
      - bluez

  - name: configure_extra_disks
    packages:
      - btrfs-progs
      - open-iscsi
    roles:
      - configure_iscsi_disks
      - setup_fstab

  - name: old_af_gpu_patch
    roles:
      - old_af_gpu_patch


setup_uwusers_definitions:
  - username: ripple
    home: /home/ripple
    sudo: true
    password: "{{ lookup('bws_cache', 'ripple_user_hashed_password').value }}"
    ssh_keys:
      - name: id_ed25519
        public_key: "{{ lookup('bws_cache', 'ripple_sshkey_pub').value }}"
        private_key: "{{ lookup('bws_cache', 'ripple_sshkey_private').value }}"
    authorized_keys:
      - "{{ lookup('bws_cache', 'ripple_sshkey_pub').value }}"
      - "{{ lookup('bws_cache', 'jankvisor_sshkey_public').value }}"
    shell: /bin/zsh
  - username: ansible
    sudo: true
    password: "{{ lookup('bws_cache', 'ansible_user_hashed_password').value }}"
    authorized_keys:
      - "{{ lookup('bws_cache', 'ripple_sshkey_pub').value }}"
      - "{{ lookup('bws_cache', 'jankvisor_sshkey_public').value }}"
    shell: /bin/bash

setup_private_ssh_keys_data:
  - username: ripple
    directory: "/home/ripple/.ssh"
    private_keys:
      - content: "{{ lookup('bws_cache', 'ripple_sshkey_private').value }}"
    public_keys:
      - content: "{{ lookup('bws_cache', 'ripple_sshkey_pub').value }}"
        key_type: "ed25519"
