all:
  hosts:
  children:
    iscsi_hosts:
      hosts:
        jankvisor-iscsi
    meaditha:
      hosts:
        meaditha-arch:
        riplappy:

    wanix_machines:
      children:
        wanix_vms:
          hosts:
            meaditha-arch:
              ansible_host: 10.0.1.190
            devbox:
              ansible_host: 10.0.1.231
        wanix_bearmetal:
          hosts:
            jankvisor:
              ansible_host: 10.0.1.30
              ansible_ssh_user: root
            riplappy:
              ansible_host: 10.0.4.94
    primary:
      hosts:
        meaditha-arch:
