iscsi_targets:
  - wwn: 'iqn.1994-05.com.redhat:linux'
    disks:
      - path: '/dev/disk/by-uuid/b899c026-4a9f-46dd-9aed-79f7acfa3f3a'
        name: 'main_linux'
        type: 'block'

    initiators:
      - 'iqn.2016-04.com.open-iscsi:linux-vm'

  - wwn: 'iqn.1994-05.com.redhat:windows'
    disks:
      - path: '/dev/disk/by-uuid/d4ba769e-7fd2-4b7c-ab34-6f5a4cb5deb4'
        name: 'main_windows'
        type: 'block'

    initiators:
      - 'iqn.2016-04.com.open-iscsi:windows-vm'


setup_nmcli_interfaces:
  - conn_name: enp6s18
    method: manual
    ip: 10.0.1.45/24
